

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@/context/UserContext';
import { BookmarkProvider } from '@/context/BookmarkContext';
import { ThemeProvider } from '@/context/ThemeContext';
import Navbar from "@/components/ui/navbar";
import AppShell from "@/components/MainLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "hrDashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-amber-50 text-black dark:bg-zinc-900 dark:text-white">
        <ThemeProvider>
          <UserProvider>
            <BookmarkProvider>
              <AppShell>{children}</AppShell>
            </BookmarkProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
